[package]
name = "blorb_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.23.0"
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "0.24", features = ["jpeg", "png"] }