[package]
name = "blorb_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.0"
egui_extras = { version = "0.31.0", features = ["all_loaders"] }
image = { version = "0.25", features = ["jpeg", "png"] }
strum = "0.27.1"
strum_macros = "0.27.1"