[package]
name = "blorb_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28"
egui_extras = { version = "0.28" }
image = { version = "0.25", features = ["jpeg", "png"] }
strum = "0.26"
strum_macros = "0.26"